#define MAINPREFIX z
#define PREFIX afms

#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH
#define VERSION_AR  MAJOR,MINOR,PATCH

#define REQUIRED_VERSION 2.10

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(AFMS - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(AFMS - COMPONENT)
#endif
